# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Pharmacate' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Google/SignIn'
pod 'Google/Analytics'
pod 'ChimpKit'
  # Pods for Pharmacate

  target 'PharmacateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PharmacateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
